# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.0"

package:
  name: "{{cookiecutter.project_slug}}"
  version: 0.1.0

source:
  - path: .
  - path: ../LICENSE
  - path: ../tests

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - pixi run mojo package {{cookiecutter.project_slug}}
    - cp {{cookiecutter.project_slug}}.mojopkg ${PREFIX}/lib/mojo/{{cookiecutter.project_slug}}.mojopkg

requirements:
  run:
    - mojo >= 0.25.6

tests:
  - script:
      # commands to run to test the package. If any of the commands
      # returns with an error code, the test is considered failed.
      - pixi run test

    files:
      # Extra files to be copied to the test directory from the "work directory"
      source:
        - {{cookiecutter.project_slug}}.mojopkg
        - pixi.toml
        - tests

about:
  homepage: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}
  license: MIT
  license_file: LICENSE
  summary: {{cookiecutter.project_short_description}}. https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}
  repository: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}
